# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_auto_20171004_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib.Libro'),
        ),
    ]
