# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0007_auto_20171004_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='vencimiento_prestamo',
            new_name='vencimiento_devolucion',
        ),
    ]
