# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0008_auto_20171004_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='fecha_prestamo',
            new_name='devolucion',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='vencimiento_devolucion',
            new_name='prestamo',
        ),
    ]
