# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0009_auto_20171005_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='devolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='prestamo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
